export { REQUEST_STATUS } from '../workflow/enums';

// ============================================
// ASSET STATUS
// ============================================

export enum ASSET_STATUS {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  FORFEITED = 'FORFEITED',
  SOLD = 'SOLD',
  RETURNED = 'RETURNED',
}

// ============================================
// ASSET TYPES
// ============================================

export enum ASSET_TYPE {
  LAPTOP = 'LAPTOP',
  TABLET = 'TABLET',
  CAMERA = 'CAMERA',
  'GAMING CONSOLE' = 'GAMING CONSOLE',
  MOBILE = 'MOBILE',
  ELECTRONICS = 'ELECTRONICS',
  TV = 'TV',
  HOME_APPLIANCE = 'HOME_APPLIANCE',
  BICYCLE = 'BICYCLE',
  TRUCK = 'TRUCK',
  MOTORCYCLE = 'MOTORCYCLE',
  CAR = 'CAR',
  JEWELRY = 'JEWELRY',
  OTHER = 'OTHER',
}

export enum ASSET_CONDITION {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  POOR = 'POOR',
}

// ============================================
// INSPECTION STATUS
// ============================================

export enum INSPECTION_STATUS {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

// ============================================
// REQUEST HISTORY ACTIONS
// ============================================

export enum REQUEST_HISTORY_ACTION {
  OFFER_CREATED = 'OFFER_CREATED',
  OFFER_REVISED = 'OFFER_REVISED',
  ASSIGNED_AGENT = 'ASSIGNED_AGENT',
  ADMIN_ASSIGNED = 'ADMIN_ASSIGNED',
  LOAN_CREATED = 'LOAN_CREATED',
  STATUS_UPDATED = 'STATUS_UPDATED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  AGREEMENT_GENERATED = 'AGREEMENT_GENERATED',
  SIGNED_AGREEMENT_UPLOADED = 'SIGNED_AGREEMENT_UPLOADED',
  INSPECTION_COMPLETED = 'INSPECTION_COMPLETED',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
  EMI_MARKED_OVERDUE = 'EMI_MARKED_OVERDUE',
  EMI_PENALTY_APPLIED = 'EMI_PENALTY_APPLIED',
  LOAN_MARKED_DEFAULTED = 'LOAN_MARKED_DEFAULTED',
  LOAN_COMPLETED = 'LOAN_COMPLETED',
}

export enum REQUEST_HISTORY_CATEGORY {
  STATUS = 'STATUS',
  OFFER = 'OFFER',
  DOCUMENT = 'DOCUMENT',
  PAYMENT = 'PAYMENT',
  INSPECTION = 'INSPECTION',
  LOAN = 'LOAN',
  COMMENT = 'COMMENT',
}