/**
 * Request status and workflow constants
 * @module request/request.constants
 */

// ============================================
// REQUEST STATUS ENUM
// ============================================

export enum REQUEST_STATUS {
  // PHASE 1: SUBMISSION & REVIEW
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  MORE_INFO_REQUIRED = 'MORE_INFO_REQUIRED',

  // PHASE 2: OFFER & NEGOTIATION
  OFFER_SENT = 'OFFER_SENT',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  OFFER_DECLINED = 'OFFER_DECLINED',
  OFFER_EXPIRED = 'OFFER_EXPIRED',

  // PHASE 3: INSPECTION
  INSPECTION_SCHEDULED = 'INSPECTION_SCHEDULED',
  INSPECTION_RESCHEDULE_REQUESTED = 'INSPECTION_RESCHEDULE_REQUESTED',
  INSPECTION_IN_PROGRESS = 'INSPECTION_IN_PROGRESS',
  INSPECTION_COMPLETED = 'INSPECTION_COMPLETED',
  CUSTOMER_NOT_AVAILABLE = 'CUSTOMER_NOT_AVAILABLE',
  ASSET_MISMATCH = 'ASSET_MISMATCH',
  AGENT_NOT_AVAILABLE = 'AGENT_NOT_AVAILABLE',

  // PHASE 4: APPROVAL & DOCUMENTATION
  APPROVED = 'APPROVED',
  PENDING_SIGNATURE = 'PENDING_SIGNATURE',
  PENDING_BANK_DETAILS = 'PENDING_BANK_DETAILS',

  // PHASE 5: LOAN PROCESSING & DISBURSEMENT
  BANK_DETAILS_SUBMITTED = 'BANK_DETAILS_SUBMITTED',
  TRANSFER_FAILED = 'TRANSFER_FAILED',
  AMOUNT_DISBURSED = 'AMOUNT_DISBURSED',

  // PHASE 6: ACTIVE LOAN
  ACTIVE = 'ACTIVE',
  PAYMENT_OVERDUE = 'PAYMENT_OVERDUE',
  DEFAULTED = 'DEFAULTED',
  COMPLETED = 'COMPLETED',

  // TERMINAL STATES
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

// ============================================
// ASSET STATUS
// ============================================

export enum ASSET_STATUS {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  FORFEITED = 'FORFEITED',
  SOLD = 'SOLD',
  RETURNED = 'RETURNED',
}

// ============================================
// ASSET TYPES
// ============================================

export enum ASSET_TYPE {
  LAPTOP = 'LAPTOP',
  TABLET = 'TABLET',
  CAMERA = 'CAMERA',
  'GAMING CONSOLE' = 'GAMING CONSOLE',
  MOBILE = 'MOBILE',
  ELECTRONICS = 'ELECTRONICS',
  TV = 'TV',
  HOME_APPLIANCE = 'HOME_APPLIANCE',
  BICYCLE = 'BICYCLE',
  TRUCK = 'TRUCK',
  MOTORCYCLE = 'MOTORCYCLE',
  CAR = 'CAR',
  JEWELRY = 'JEWELRY',
  OTHER = 'OTHER',
}

export enum ASSET_CONDITION {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  POOR = 'POOR',
}

export const ASSET_TYPE_OPTIONS = [
  { value: 'LAPTOP', label: 'Laptop' },
  { value: 'TABLET', label: 'Tablet' },
  { value: 'CAMERA', label: 'Camera' },
  { value: 'GAMING CONSOLE', label: 'Gaming Console' },
  { value: 'MOBILE', label: 'Mobile / Phone' },
  { value: 'ELECTRONICS', label: 'Electronics (TV, Audio)' },
  { value: 'TV', label: 'TV' },
  { value: 'HOME_APPLIANCE', label: 'Home Appliance' },
  { value: 'BICYCLE', label: 'Bicycle' },
  { value: 'TRUCK', label: 'Truck' },
  { value: 'MOTORCYCLE', label: 'Motorcycle' },
  { value: 'CAR', label: 'Car' },
  { value: 'JEWELRY', label: 'Jewelry' },
  { value: 'OTHER', label: 'Other' },
] as const;

export const ASSET_CONDITION_OPTIONS = [
  { value: 'EXCELLENT', label: 'Excellent - Like new' },
  { value: 'GOOD', label: 'Good - Minor wear' },
  { value: 'FAIR', label: 'Fair - Visible wear' },
  { value: 'POOR', label: 'Poor - Significant wear' },
] as const;

// ============================================
// INSPECTION STATUS
// ============================================

export enum INSPECTION_STATUS {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

// ============================================
// STATUS GROUPINGS
// ============================================

/** Statuses where customer can still update their request */
export const ALLOWED_UPDATE_STATUSES: REQUEST_STATUS[] = [
  REQUEST_STATUS.PENDING,
  REQUEST_STATUS.OFFER_DECLINED,
  REQUEST_STATUS.REJECTED,
  REQUEST_STATUS.CANCELLED,
];

/** Statuses where the request is still pending/in progress */
export const PENDING_REQUEST_STATUSES: REQUEST_STATUS[] = [
  REQUEST_STATUS.PENDING,
  REQUEST_STATUS.UNDER_REVIEW,
  REQUEST_STATUS.MORE_INFO_REQUIRED,
  REQUEST_STATUS.OFFER_SENT,
  REQUEST_STATUS.OFFER_ACCEPTED,
  REQUEST_STATUS.OFFER_DECLINED,
  REQUEST_STATUS.OFFER_EXPIRED,
  REQUEST_STATUS.INSPECTION_SCHEDULED,
  REQUEST_STATUS.INSPECTION_IN_PROGRESS,
  REQUEST_STATUS.INSPECTION_COMPLETED,
  REQUEST_STATUS.CUSTOMER_NOT_AVAILABLE,
  REQUEST_STATUS.ASSET_MISMATCH,
  REQUEST_STATUS.AGENT_NOT_AVAILABLE,
];

/** Statuses where customer action is required */
export const CUSTOMER_ACTION_REQUIRED: REQUEST_STATUS[] = [
  REQUEST_STATUS.MORE_INFO_REQUIRED,
  REQUEST_STATUS.OFFER_SENT,
  REQUEST_STATUS.PENDING_SIGNATURE,
  REQUEST_STATUS.PENDING_BANK_DETAILS,
  REQUEST_STATUS.TRANSFER_FAILED,
];

/** Statuses where admin action is required */
export const ADMIN_ACTION_REQUIRED: REQUEST_STATUS[] = [
  REQUEST_STATUS.PENDING,
  REQUEST_STATUS.UNDER_REVIEW,
  REQUEST_STATUS.OFFER_EXPIRED,
  REQUEST_STATUS.INSPECTION_COMPLETED,
  REQUEST_STATUS.BANK_DETAILS_SUBMITTED,
];

/** Statuses where agent action is required */
export const AGENT_ACTION_REQUIRED: REQUEST_STATUS[] = [
  REQUEST_STATUS.INSPECTION_SCHEDULED,
  REQUEST_STATUS.INSPECTION_IN_PROGRESS,
];

/** Statuses where agents should no longer have UI access */
export const AGENT_ACCESS_DENY_STATUSES: REQUEST_STATUS[] = [
  REQUEST_STATUS.BANK_DETAILS_SUBMITTED,
  REQUEST_STATUS.TRANSFER_FAILED,
  REQUEST_STATUS.AMOUNT_DISBURSED,
  REQUEST_STATUS.ACTIVE,
  REQUEST_STATUS.PAYMENT_OVERDUE,
  REQUEST_STATUS.DEFAULTED,
  REQUEST_STATUS.COMPLETED,
];

/** Statuses that allow customer transitions */
export const CUSTOMER_ALLOWED_STATUSES: REQUEST_STATUS[] = [
  REQUEST_STATUS.OFFER_ACCEPTED,
  REQUEST_STATUS.OFFER_DECLINED,
  REQUEST_STATUS.CANCELLED,
  REQUEST_STATUS.PENDING,
  REQUEST_STATUS.INSPECTION_SCHEDULED,
  REQUEST_STATUS.INSPECTION_RESCHEDULE_REQUESTED,
  REQUEST_STATUS.PENDING_BANK_DETAILS,
  REQUEST_STATUS.BANK_DETAILS_SUBMITTED,
];

/** Statuses that allow agent transitions */
export const AGENT_ALLOWED_STATUSES: REQUEST_STATUS[] = [
  REQUEST_STATUS.INSPECTION_IN_PROGRESS,
  REQUEST_STATUS.INSPECTION_COMPLETED,
  REQUEST_STATUS.INSPECTION_SCHEDULED,
  REQUEST_STATUS.CUSTOMER_NOT_AVAILABLE,
  REQUEST_STATUS.ASSET_MISMATCH,
  REQUEST_STATUS.AGENT_NOT_AVAILABLE,
  REQUEST_STATUS.APPROVED,
  REQUEST_STATUS.REJECTED,
];

/** Statuses that allow loan creation */
export const LOAN_CREATION_ALLOWED_STATUSES: REQUEST_STATUS[] = [
  REQUEST_STATUS.OFFER_ACCEPTED,
  REQUEST_STATUS.INSPECTION_COMPLETED,
  REQUEST_STATUS.APPROVED,
];

// ============================================
// REQUEST HISTORY ACTIONS
// ============================================

export enum REQUEST_HISTORY_ACTION {
  OFFER_CREATED = 'OFFER_CREATED',
  OFFER_REVISED = 'OFFER_REVISED',
  ASSIGNED_AGENT = 'ASSIGNED_AGENT',
  ADMIN_ASSIGNED = 'ADMIN_ASSIGNED',
  LOAN_CREATED = 'LOAN_CREATED',
  STATUS_UPDATED = 'STATUS_UPDATED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  AGREEMENT_GENERATED = 'AGREEMENT_GENERATED',
  SIGNED_AGREEMENT_UPLOADED = 'SIGNED_AGREEMENT_UPLOADED',
  INSPECTION_COMPLETED = 'INSPECTION_COMPLETED',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
  EMI_MARKED_OVERDUE = 'EMI_MARKED_OVERDUE',
  EMI_PENALTY_APPLIED = 'EMI_PENALTY_APPLIED',
  LOAN_MARKED_DEFAULTED = 'LOAN_MARKED_DEFAULTED',
  LOAN_COMPLETED = 'LOAN_COMPLETED',
}

export enum REQUEST_HISTORY_CATEGORY {
  STATUS = 'STATUS',
  OFFER = 'OFFER',
  DOCUMENT = 'DOCUMENT',
  PAYMENT = 'PAYMENT',
  INSPECTION = 'INSPECTION',
  LOAN = 'LOAN',
  COMMENT = 'COMMENT',
}

// ============================================
// WORKFLOW PHASES
// ============================================

export enum REQUEST_PHASE {
  SUBMISSION = 'SUBMISSION',
  OFFER = 'OFFER',
  INSPECTION = 'INSPECTION',
  APPROVAL = 'APPROVAL',
  DISBURSEMENT = 'DISBURSEMENT',
  REPAYMENT = 'REPAYMENT',
}

export const REQUEST_PHASE_LABELS: Record<REQUEST_PHASE, string> = {
  [REQUEST_PHASE.SUBMISSION]: 'Submit',
  [REQUEST_PHASE.OFFER]: 'Offer',
  [REQUEST_PHASE.INSPECTION]: 'Inspect',
  [REQUEST_PHASE.APPROVAL]: 'Approve',
  [REQUEST_PHASE.DISBURSEMENT]: 'Disburse',
  [REQUEST_PHASE.REPAYMENT]: 'Repay',
};

/** Map status to phase */
export const REQUEST_STATUS_PHASE: Record<REQUEST_STATUS, REQUEST_PHASE> = {
  [REQUEST_STATUS.PENDING]: REQUEST_PHASE.SUBMISSION,
  [REQUEST_STATUS.UNDER_REVIEW]: REQUEST_PHASE.SUBMISSION,
  [REQUEST_STATUS.MORE_INFO_REQUIRED]: REQUEST_PHASE.SUBMISSION,
  [REQUEST_STATUS.OFFER_SENT]: REQUEST_PHASE.OFFER,
  [REQUEST_STATUS.OFFER_ACCEPTED]: REQUEST_PHASE.OFFER,
  [REQUEST_STATUS.OFFER_DECLINED]: REQUEST_PHASE.OFFER,
  [REQUEST_STATUS.OFFER_EXPIRED]: REQUEST_PHASE.OFFER,
  [REQUEST_STATUS.INSPECTION_SCHEDULED]: REQUEST_PHASE.INSPECTION,
  [REQUEST_STATUS.INSPECTION_RESCHEDULE_REQUESTED]: REQUEST_PHASE.INSPECTION,
  [REQUEST_STATUS.INSPECTION_IN_PROGRESS]: REQUEST_PHASE.INSPECTION,
  [REQUEST_STATUS.INSPECTION_COMPLETED]: REQUEST_PHASE.INSPECTION,
  [REQUEST_STATUS.CUSTOMER_NOT_AVAILABLE]: REQUEST_PHASE.INSPECTION,
  [REQUEST_STATUS.ASSET_MISMATCH]: REQUEST_PHASE.INSPECTION,
  [REQUEST_STATUS.AGENT_NOT_AVAILABLE]: REQUEST_PHASE.INSPECTION,
  [REQUEST_STATUS.APPROVED]: REQUEST_PHASE.APPROVAL,
  [REQUEST_STATUS.PENDING_SIGNATURE]: REQUEST_PHASE.APPROVAL,
  [REQUEST_STATUS.PENDING_BANK_DETAILS]: REQUEST_PHASE.DISBURSEMENT,
  [REQUEST_STATUS.BANK_DETAILS_SUBMITTED]: REQUEST_PHASE.DISBURSEMENT,
  [REQUEST_STATUS.TRANSFER_FAILED]: REQUEST_PHASE.DISBURSEMENT,
  [REQUEST_STATUS.AMOUNT_DISBURSED]: REQUEST_PHASE.DISBURSEMENT,
  [REQUEST_STATUS.ACTIVE]: REQUEST_PHASE.REPAYMENT,
  [REQUEST_STATUS.PAYMENT_OVERDUE]: REQUEST_PHASE.REPAYMENT,
  [REQUEST_STATUS.DEFAULTED]: REQUEST_PHASE.REPAYMENT,
  [REQUEST_STATUS.COMPLETED]: REQUEST_PHASE.REPAYMENT,
  [REQUEST_STATUS.REJECTED]: REQUEST_PHASE.SUBMISSION,
  [REQUEST_STATUS.CANCELLED]: REQUEST_PHASE.SUBMISSION,
};

/** Get phase number (1-6) for progress bar */
export const getPhaseNumber = (status: REQUEST_STATUS): number => {
  const phaseOrder: REQUEST_PHASE[] = [
    REQUEST_PHASE.SUBMISSION,
    REQUEST_PHASE.OFFER,
    REQUEST_PHASE.INSPECTION,
    REQUEST_PHASE.APPROVAL,
    REQUEST_PHASE.DISBURSEMENT,
    REQUEST_PHASE.REPAYMENT,
  ];
  const phase = REQUEST_STATUS_PHASE[status];
  return phaseOrder.indexOf(phase) + 1;
};

// ============================================
// OFFER FORM CONSTANTS
// ============================================

export const OFFER_FORM_DEFAULTS = {
  PENALTY_PERCENTAGE: 4,
  LATE_FEE_PERCENTAGE: 0.01,
  PROCESSING_FEE: 0,
} as const;

export const OFFER_FORM_CONSTRAINTS = {
  MAX_TENURE_MONTHS: 60,
  MAX_INTEREST_RATE: 36,
  MIN_AMOUNT: 0,
  MIN_TENURE: 1,
  MIN_INTEREST_RATE: 0,
} as const;

