/**
 * Audit-related constants
 * Aligned with Prisma schema
 */

export const AUDIT_ACTIONS = {
  // Auth
  LOGIN: 'AUTH_LOGIN',
  LOGOUT: 'AUTH_LOGOUT',
  REGISTER: 'AUTH_REGISTER',
  PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  PASSWORD_CHANGE: 'AUTH_PASSWORD_CHANGE',
  
  // Request
  REQUEST_CREATE: 'REQUEST_CREATE',
  REQUEST_UPDATE: 'REQUEST_UPDATE',
  REQUEST_STAGE_CHANGE: 'REQUEST_STAGE_CHANGE',
  REQUEST_DELETE: 'REQUEST_DELETE',
  REQUEST_ASSIGN_AGENT: 'REQUEST_ASSIGN_AGENT',
  REQUEST_ASSIGN_ADMIN: 'REQUEST_ASSIGN_ADMIN',
  
  // Loan
  LOAN_CREATE: 'LOAN_CREATE',
  LOAN_DISBURSE: 'LOAN_DISBURSE',
  LOAN_CLOSE: 'LOAN_CLOSE',
  LOAN_DEFAULT: 'LOAN_DEFAULT',
  
  // Payment
  PAYMENT_CREATE: 'PAYMENT_CREATE',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  
  // User
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ROLE_CHANGE: 'USER_ROLE_CHANGE',
  
  // Asset
  ASSET_CREATE: 'ASSET_CREATE',
  ASSET_UPDATE: 'ASSET_UPDATE',
  ASSET_MOVEMENT: 'ASSET_MOVEMENT',
  
  // Auction
  AUCTION_CREATE: 'AUCTION_CREATE',
  AUCTION_START: 'AUCTION_START',
  AUCTION_END: 'AUCTION_END',
  BID_PLACE: 'BID_PLACE',
} as const;

export const AUDIT_ENTITY_TYPES = {
  USER: 'USER',
  REQUEST: 'REQUEST',
  LOAN: 'LOAN',
  PAYMENT: 'PAYMENT',
  EMI_SCHEDULE: 'EMI_SCHEDULE',
  ASSET: 'ASSET',
  AUCTION: 'AUCTION',
  BID: 'BID',
  DOCUMENT: 'DOCUMENT',
  SESSION: 'SESSION',
} as const;

export const AUDIT_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PARTIAL: 'PARTIAL',
} as const;
